export type FinderMode =
  | "identify"
  | "chord-list"
  | "diatonic"
  | "substitution"
  | "capo"
  | "related-keys"
  | "modes"
  | "progression-analysis"
  | "scale-compat"
  | "tension-avoid"
  | "modal-interchange"
  | "circle"
  | "chord-suggest"
  | "dominant-motion"
  | "common"
  | "modulation";
